[tool.poetry]
name = "renspell"
version = "0.2.0"
description = "A spell-checker for Ren'Py scripts"
authors = ["Harlan Lieberman-Berg <hlieberman@setec.io>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
language-tool-python = "^2.4.7"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.790"
black = "^20.8b1"

[tool.poetry.scripts]
renspell = "renspell.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
