[tool.poetry]
name = "pytimetools"
version = "0.1.3.5"
description = "a time tools for django"
authors = ["huoyinghui <hyhlinux@163.com>"]
homepage = "https://github.com/pydtools/pytimetools/"
repository = "https://github.com/pydtools/pytimetools/"
documentation = "https://github.com/pydtools/pytimetools/wiki"
include = ["CHANGELOG.md"]

[tool.poetry.dependencies]
python = "~2.7 || ^3.5"
django = "^1.10"
pytz = "^2017.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/pydtools/pytimetools/issues"
"github" = "https://github.com/pydtools/pytimetools/"
