[tool.poetry]
name = "logger-bundle"
version = "0.6.0a3"
description = "Logger bundle for the Pyfony framework"
readme = "README.md"
repository = "https://github.com/pyfony/logger-bundle"

license = "MIT"

authors = [
    "Jiri Koutny <jiri.koutny@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["*.yaml"]

packages = [
    { include = "loggerbundle", from = "src" },
]

[tool.poetry.dependencies]
python = "~3.7.3"
colorlog = "4.0.*"
pyfony-bundles = "0.2.5a2"

[tool.poetry.dev-dependencies]
pylint = "2.4.*"
pytest = "5.2.*"
pyfony-core = "0.7.0a3"

[tool.poetry.plugins."pyfony.bundle"]
autodetect = "loggerbundle.LoggerBundle:LoggerBundle.autodetect"
