[tool.poetry]
name = "acquisition_sanitizer"
version = "0.1.0"
description = "Helper function for pattern matching functions"
authors = ["Mars Veloso <testmarcelino@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
html-sanitizer = "^1.9.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-instafail = "^0.4.2"
pytest-sugar = "^0.9.4"
pytest-icdiff = "^0.5"
pytest-cov = "^2.10.1"
mypy = "^0.790"
black = "^20.8b1"
isort = "^5.6.4"
pre-commit = "^2.6.0"
ipykernel = "^5.3.4"

[tool.pytest]
minversion = "6.0"
addopts = "-ra -q --cov=startcode tests/"
testpaths = ["tests"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79
include_trailing_comma = 'True'

[tool.black]
line-length = 79
include = '.pyi?$'
exclude = '''
/(
    .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
)/
'''


[build-system]
requires = ["poetry-core>=1.1.4"]
build-backend = "poetry.core.masonry.api"
