[tool.poetry]
name = "aceui"
version = "1.0.20"
description = "基于Selenium的UI自动化测试框架"
license = "Apache-2.0"
readme = "README.md"
authors = ["天枢 <lengyaohui@163.com>"]

homepage = "https://github.com/HttpTesting/aceui"
repository = "https://github.com/HttpTesting/aceui"


keywords = ["selenium", "po", "HTMLTestRunner", "test"]
classifiers  =  [ 
    "Environment :: Console",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: Microsoft :: Windows",
    "Development Status :: 3 - Alpha",
]

include = ["LICENSE", "aceui/base/*", "aceui/config/*", "aceui/lib/*", "aceui/whls/*"]

[tool.poetry.dependencies]

ddt = "1.1.3"
Pillow = "5.3.0"
PyAutoIt = "0.6.0"
PyYAML = "5.1.1"
selenium = "3.141.0"
requests = "2.25.0"
xlrd = "1.2.0"
xlutils = "2.0.0"
xlwt = "1.3.0"

[tool.poetry.dev-dependencies]


[tool.poetry.scripts]
aceui = "aceui.cli:run_min"
ace = "aceui.cli:run_min"


[build-system]
requires = ["poetry>=0.12.17"]
build-backend = "poetry.masonry.api"