[tool.poetry]
name = "pyfony-bundles"
version = "0.2.5a2"
description = "Pyfony Framework bundles base package"
readme = "README.md"
repository = "https://github.com/pyfony/pyfony-bundles"

license = "MIT"

authors = [
    "Jiri Koutny <jiri.koutny@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["*.yaml"]

packages = [
    { include = "pyfonybundles", from = "src" },
]

[tool.poetry.dependencies]
python = "~3.7.3"
tomlkit = "0.5.*"
injecta = "0.6.* || 0.7.* || 0.8.*"
python-box = "3.4.*"

[tool.poetry.dev-dependencies]
pylint = "2.4.*"
