[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "mopidy_async_client"
author = "svinerus"
author-email = "svinerus@gmail.com"
home-page = "https://github.com/SvineruS/mopidy-async-client"
description-file = "README.md"
requires-python = ">=3.7"
dist-name = "mopidy-async-client"
keywords = "mopidy, mpd, async, asyncio, client, player"
requires = ["websockets"]
